name: learn-github-actions

on:
  push:
    branches: [feature/docker-init]

env:
  SPA_PATH: "./RequestLoggerSpa/request-logger"
  API_PATH: "./RequestLoggerApi/RequestLogger"
  NODE_VERSION: 14
  DOTNET_VERSION: "5.0.203"

jobs:
  build-spa:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{env.NODE_VERSION}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Setup .NET 5 SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install npm packages
        run: |
          cd $SPA_PATH
          npm ci

      - name: Build SPA
        run: |
          cd $SPA_PATH
          npm run build-prod

      - name: Copy SPA dist to wwwroot
        run: mv ${{env.SPA_PATH}}/dist/request-logger/* ${{env.API_PATH}}/wwwroot/

      - name: Publish API
        run: dotnet publish ${{env.API_PATH}}

      - name: Store output
        uses: actions/upload-artifact@v2
        with:
          name: API
          path: ${{env.API_PATH}}/bin/Release/net5.0/publish
