name: Build and deploy

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master, develop]

env:
  SPA_PATH: "./RequestLoggerSpa/request-logger"
  API_PATH: "./RequestLoggerApi/RequestLogger"
  NODE_VERSION: 14
  DOTNET_VERSION: "5.0.203"

jobs:
  build-spa:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{env.NODE_VERSION}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Setup .NET 5 SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install npm packages
        run: |
          cd $SPA_PATH
          npm ci
          npm run test:prod
          npm run lint
          npm run build:prod

      - name: Copy SPA dist to wwwroot
        run: |
          mkdir -p ${{env.API_PATH}}/wwwroot/
          mv ${{env.SPA_PATH}}/dist/request-logger/* ${{env.API_PATH}}/wwwroot/

      - name: Publish API
        run: |
          dotnet test ${{env.API_PATH}}
          dotnet publish ${{env.API_PATH}} -c Release

      - name: Store output
        uses: actions/upload-artifact@v2
        with:
          name: API
          path: ${{env.API_PATH}}/bin/Release/net5.0/publish/*

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_HDT_SECRET }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lderossis/hdt:development
          context: ${{env.API_PATH}}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lderossis/hdt:latest
          context: ${{env.API_PATH}}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{env.SPA_PATH}}
          args: >
            -Dsonar.organization=lderossis
            -Dsonar.projectKey=l-derossis_http-debug-toolkit
            -Dsonar.sources=src/
            -Dsonar.javascript.lcov.reportPaths=coverage/request-logger/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
