name: Static code analysis

on:
  push:
    branches:
      - "**"

env:
  SPA_PATH: "./RequestLoggerSpa/request-logger"

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{env.SPA_PATH}}
          args: >
            -Dsonar.organization=lderossis
            -Dsonar.projectKey=l-derossis_http-debug-toolkit
            -Dsonar.sources=src/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
